---
controller_templates:
  - name: "PATCHING - Install Available Updates"
    description: ""
    organization: "Default"
    project: "Ansible Patching Utilities"
    inventory: "Ansible Test Inventory"
    playbook: "playbooks/install_available_updates.yml"
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials:
      - "Ansible Test Credential"
    allow_simultaneous: false
    ask_scm_branch_on_launch: false
    ask_diff_mode_on_launch: false
    ask_tags_on_launch: false
    ask_skip_tags_on_launch: false
    ask_job_type_on_launch: false
    ask_verbosity_on_launch: false
    ask_variables_on_launch: false
    ask_inventory_on_launch: false
    ask_limit_on_launch: false
    ask_credential_on_launch: false
    job_tags: ""
    force_handlers: false
    skip_tags: ""
    start_at_task: ""
    timeout: 0
    custom_virtualenv: ""
    host_config_key: ""
    survey_enabled: false
    become_enabled: false
    diff_mode: false
    webhook_service: ""
  - name: "PATCHING - Reboot"
    description: ""
    organization: "Default"
    project: "Ansible Patching Utilities"
    inventory: "Ansible Test Inventory"
    playbook: "playbooks/reboot.yml"
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials:
      - "Ansible Test Credential"
    allow_simultaneous: false
    ask_scm_branch_on_launch: false
    ask_diff_mode_on_launch: false
    ask_tags_on_launch: false
    ask_skip_tags_on_launch: false
    ask_job_type_on_launch: false
    ask_verbosity_on_launch: false
    ask_variables_on_launch: false
    ask_inventory_on_launch: false
    ask_limit_on_launch: false
    ask_credential_on_launch: false
    job_tags: ""
    force_handlers: false
    skip_tags: ""
    start_at_task: ""
    timeout: 0
    custom_virtualenv: ""
    host_config_key: ""
    survey_enabled: false
    become_enabled: false
    diff_mode: false
    webhook_service: ""
...
