---
collections:
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
  - name: ansible.eda
  - name: infra.aap_configuration
  - name: infra.controller_configuration
    version: 2.9.0
  - name: infra.ah_configuration
  - name: infra.aap_utilities
  - name: infra.ee_utilities
  - name: infra.eda_configuration
  - name: awx.awx
